import { NextResponse } from "next/server"

/**
 * /api/usa-stocks — S&P 500 completo (~503 tickers) con precios en vivo.
 * Usa Yahoo Finance batch quote (/v7/finance/quote?symbols=A,B,C...) para
 * traer hasta 100 tickers por request; 5 batches en paralelo = ~1s total.
 */

const YF_HEADERS = {
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  Accept: "application/json",
  Origin: "https://finance.yahoo.com",
  Referer: "https://finance.yahoo.com/",
}

type Sector = "Tecnología" | "Salud" | "Finanzas" | "Consumo Discr." | "Consumo Básico" | "Energía" | "Industrial" | "Materiales" | "Servicios Púb." | "Real Estate" | "Comunicaciones"

const SP500: Array<{ ticker: string; name: string; sector: Sector }> = [
  // ── Tecnología ──────────────────────────────────────────────────────────────
  { ticker: "AAPL",  name: "Apple",                  sector: "Tecnología" },
  { ticker: "MSFT",  name: "Microsoft",              sector: "Tecnología" },
  { ticker: "NVDA",  name: "NVIDIA",                 sector: "Tecnología" },
  { ticker: "AVGO",  name: "Broadcom",               sector: "Tecnología" },
  { ticker: "ORCL",  name: "Oracle",                 sector: "Tecnología" },
  { ticker: "CSCO",  name: "Cisco",                  sector: "Tecnología" },
  { ticker: "ACN",   name: "Accenture",              sector: "Tecnología" },
  { ticker: "ADBE",  name: "Adobe",                  sector: "Tecnología" },
  { ticker: "CRM",   name: "Salesforce",             sector: "Tecnología" },
  { ticker: "AMD",   name: "AMD",                    sector: "Tecnología" },
  { ticker: "TXN",   name: "Texas Instruments",      sector: "Tecnología" },
  { ticker: "INTC",  name: "Intel",                  sector: "Tecnología" },
  { ticker: "QCOM",  name: "Qualcomm",               sector: "Tecnología" },
  { ticker: "IBM",   name: "IBM",                    sector: "Tecnología" },
  { ticker: "NOW",   name: "ServiceNow",             sector: "Tecnología" },
  { ticker: "INTU",  name: "Intuit",                 sector: "Tecnología" },
  { ticker: "AMAT",  name: "Applied Materials",      sector: "Tecnología" },
  { ticker: "ADI",   name: "Analog Devices",         sector: "Tecnología" },
  { ticker: "PANW",  name: "Palo Alto Networks",     sector: "Tecnología" },
  { ticker: "KLAC",  name: "KLA Corp",               sector: "Tecnología" },
  { ticker: "LRCX",  name: "Lam Research",           sector: "Tecnología" },
  { ticker: "SNPS",  name: "Synopsys",               sector: "Tecnología" },
  { ticker: "CDNS",  name: "Cadence Design",         sector: "Tecnología" },
  { ticker: "FTNT",  name: "Fortinet",               sector: "Tecnología" },
  { ticker: "APH",   name: "Amphenol",               sector: "Tecnología" },
  { ticker: "ANET",  name: "Arista Networks",        sector: "Tecnología" },
  { ticker: "GLW",   name: "Corning",                sector: "Tecnología" },
  { ticker: "MSI",   name: "Motorola Solutions",     sector: "Tecnología" },
  { ticker: "ROP",   name: "Roper Technologies",     sector: "Tecnología" },
  { ticker: "KEYS",  name: "Keysight Technologies",  sector: "Tecnología" },
  { ticker: "TEL",   name: "TE Connectivity",        sector: "Tecnología" },
  { ticker: "HPE",   name: "HP Enterprise",          sector: "Tecnología" },
  { ticker: "HPQ",   name: "HP Inc",                 sector: "Tecnología" },
  { ticker: "CDW",   name: "CDW Corp",               sector: "Tecnología" },
  { ticker: "NTAP",  name: "NetApp",                 sector: "Tecnología" },
  { ticker: "WDC",   name: "Western Digital",        sector: "Tecnología" },
  { ticker: "STX",   name: "Seagate Technology",     sector: "Tecnología" },
  { ticker: "VRSN",  name: "VeriSign",               sector: "Tecnología" },
  { ticker: "PTC",   name: "PTC Inc",                sector: "Tecnología" },
  { ticker: "FFIV",  name: "F5 Inc",                 sector: "Tecnología" },
  { ticker: "ANSS",  name: "ANSYS",                  sector: "Tecnología" },
  { ticker: "TDY",   name: "Teledyne Technologies",  sector: "Tecnología" },
  { ticker: "IT",    name: "Gartner",                sector: "Tecnología" },
  { ticker: "AKAM",  name: "Akamai Technologies",    sector: "Tecnología" },
  { ticker: "EPAM",  name: "EPAM Systems",           sector: "Tecnología" },
  { ticker: "JNPR",  name: "Juniper Networks",       sector: "Tecnología" },
  { ticker: "GEN",   name: "Gen Digital",            sector: "Tecnología" },
  { ticker: "NXPI",  name: "NXP Semiconductors",     sector: "Tecnología" },
  { ticker: "MPWR",  name: "Monolithic Power",       sector: "Tecnología" },
  { ticker: "MCHP",  name: "Microchip Technology",   sector: "Tecnología" },
  { ticker: "ON",    name: "ON Semiconductor",       sector: "Tecnología" },
  { ticker: "SWKS",  name: "Skyworks Solutions",     sector: "Tecnología" },
  { ticker: "QRVO",  name: "Qorvo",                  sector: "Tecnología" },
  { ticker: "TER",   name: "Teradyne",               sector: "Tecnología" },
  { ticker: "GDDY",  name: "GoDaddy",                sector: "Tecnología" },
  { ticker: "CTSH",  name: "Cognizant Technology",   sector: "Tecnología" },
  { ticker: "PLTR",  name: "Palantir Technologies",  sector: "Tecnología" },
  { ticker: "CRWD",  name: "CrowdStrike",            sector: "Tecnología" },
  // ── Comunicaciones ──────────────────────────────────────────────────────────
  { ticker: "META",  name: "Meta Platforms",         sector: "Comunicaciones" },
  { ticker: "GOOGL", name: "Alphabet A",             sector: "Comunicaciones" },
  { ticker: "GOOG",  name: "Alphabet C",             sector: "Comunicaciones" },
  { ticker: "NFLX",  name: "Netflix",                sector: "Comunicaciones" },
  { ticker: "CMCSA", name: "Comcast",                sector: "Comunicaciones" },
  { ticker: "DIS",   name: "Walt Disney",            sector: "Comunicaciones" },
  { ticker: "VZ",    name: "Verizon",                sector: "Comunicaciones" },
  { ticker: "T",     name: "AT&T",                   sector: "Comunicaciones" },
  { ticker: "TMUS",  name: "T-Mobile US",            sector: "Comunicaciones" },
  { ticker: "WBD",   name: "Warner Bros. Discovery", sector: "Comunicaciones" },
  { ticker: "PARA",  name: "Paramount Global",       sector: "Comunicaciones" },
  { ticker: "NWSA",  name: "News Corp A",            sector: "Comunicaciones" },
  { ticker: "NWS",   name: "News Corp B",            sector: "Comunicaciones" },
  { ticker: "TTWO",  name: "Take-Two Interactive",   sector: "Comunicaciones" },
  { ticker: "EA",    name: "Electronic Arts",        sector: "Comunicaciones" },
  { ticker: "MTCH",  name: "Match Group",            sector: "Comunicaciones" },
  { ticker: "LYV",   name: "Live Nation",            sector: "Comunicaciones" },
  { ticker: "IPG",   name: "Interpublic Group",      sector: "Comunicaciones" },
  { ticker: "OMC",   name: "Omnicom Group",          sector: "Comunicaciones" },
  { ticker: "FOXA",  name: "Fox Corp A",             sector: "Comunicaciones" },
  { ticker: "FOX",   name: "Fox Corp B",             sector: "Comunicaciones" },
  // ── Consumo Discrecional ─────────────────────────────────────────────────────
  { ticker: "AMZN",  name: "Amazon",                 sector: "Consumo Discr." },
  { ticker: "TSLA",  name: "Tesla",                  sector: "Consumo Discr." },
  { ticker: "HD",    name: "Home Depot",             sector: "Consumo Discr." },
  { ticker: "MCD",   name: "McDonald's",             sector: "Consumo Discr." },
  { ticker: "NKE",   name: "Nike",                   sector: "Consumo Discr." },
  { ticker: "LOW",   name: "Lowe's",                 sector: "Consumo Discr." },
  { ticker: "SBUX",  name: "Starbucks",              sector: "Consumo Discr." },
  { ticker: "TJX",   name: "TJX Companies",          sector: "Consumo Discr." },
  { ticker: "BKNG",  name: "Booking Holdings",       sector: "Consumo Discr." },
  { ticker: "ORLY",  name: "O'Reilly Automotive",    sector: "Consumo Discr." },
  { ticker: "LVS",   name: "Las Vegas Sands",        sector: "Consumo Discr." },
  { ticker: "MGM",   name: "MGM Resorts",            sector: "Consumo Discr." },
  { ticker: "NCLH",  name: "Norwegian Cruise",       sector: "Consumo Discr." },
  { ticker: "CCL",   name: "Carnival Corp",          sector: "Consumo Discr." },
  { ticker: "RCL",   name: "Royal Caribbean",        sector: "Consumo Discr." },
  { ticker: "HLT",   name: "Hilton Worldwide",       sector: "Consumo Discr." },
  { ticker: "MAR",   name: "Marriott International", sector: "Consumo Discr." },
  { ticker: "WYNN",  name: "Wynn Resorts",           sector: "Consumo Discr." },
  { ticker: "ROST",  name: "Ross Stores",            sector: "Consumo Discr." },
  { ticker: "EBAY",  name: "eBay",                   sector: "Consumo Discr." },
  { ticker: "F",     name: "Ford Motor",             sector: "Consumo Discr." },
  { ticker: "GM",    name: "General Motors",         sector: "Consumo Discr." },
  { ticker: "APTV",  name: "Aptiv",                  sector: "Consumo Discr." },
  { ticker: "TPR",   name: "Tapestry",               sector: "Consumo Discr." },
  { ticker: "RL",    name: "Ralph Lauren",           sector: "Consumo Discr." },
  { ticker: "HAS",   name: "Hasbro",                 sector: "Consumo Discr." },
  { ticker: "MAT",   name: "Mattel",                 sector: "Consumo Discr." },
  { ticker: "YUM",   name: "Yum! Brands",            sector: "Consumo Discr." },
  { ticker: "DRI",   name: "Darden Restaurants",     sector: "Consumo Discr." },
  { ticker: "CMG",   name: "Chipotle Mexican Grill", sector: "Consumo Discr." },
  { ticker: "DPZ",   name: "Domino's Pizza",         sector: "Consumo Discr." },
  { ticker: "TSCO",  name: "Tractor Supply",         sector: "Consumo Discr." },
  { ticker: "BBY",   name: "Best Buy",               sector: "Consumo Discr." },
  { ticker: "AZO",   name: "AutoZone",               sector: "Consumo Discr." },
  { ticker: "KMX",   name: "CarMax",                 sector: "Consumo Discr." },
  { ticker: "DLTR",  name: "Dollar Tree",            sector: "Consumo Discr." },
  { ticker: "DG",    name: "Dollar General",         sector: "Consumo Discr." },
  { ticker: "LULU",  name: "Lululemon Athletica",    sector: "Consumo Discr." },
  { ticker: "PHM",   name: "PulteGroup",             sector: "Consumo Discr." },
  { ticker: "DHI",   name: "D.R. Horton",            sector: "Consumo Discr." },
  { ticker: "LEN",   name: "Lennar",                 sector: "Consumo Discr." },
  { ticker: "NVR",   name: "NVR Inc",                sector: "Consumo Discr." },
  { ticker: "POOL",  name: "Pool Corp",              sector: "Consumo Discr." },
  { ticker: "MHK",   name: "Mohawk Industries",      sector: "Consumo Discr." },
  { ticker: "ABNB",  name: "Airbnb",                 sector: "Consumo Discr." },
  { ticker: "UBER",  name: "Uber Technologies",      sector: "Consumo Discr." },
  { ticker: "EXPE",  name: "Expedia Group",          sector: "Consumo Discr." },
  { ticker: "BWA",   name: "BorgWarner",             sector: "Consumo Discr." },
  // ── Consumo Básico ────────────────────────────────────────────────────────────
  { ticker: "WMT",   name: "Walmart",                sector: "Consumo Básico" },
  { ticker: "COST",  name: "Costco",                 sector: "Consumo Básico" },
  { ticker: "PG",    name: "Procter & Gamble",       sector: "Consumo Básico" },
  { ticker: "KO",    name: "Coca-Cola",              sector: "Consumo Básico" },
  { ticker: "PEP",   name: "PepsiCo",                sector: "Consumo Básico" },
  { ticker: "MO",    name: "Altria Group",           sector: "Consumo Básico" },
  { ticker: "PM",    name: "Philip Morris",          sector: "Consumo Básico" },
  { ticker: "MDLZ",  name: "Mondelez International", sector: "Consumo Básico" },
  { ticker: "CL",    name: "Colgate-Palmolive",      sector: "Consumo Básico" },
  { ticker: "KHC",   name: "Kraft Heinz",            sector: "Consumo Básico" },
  { ticker: "GIS",   name: "General Mills",          sector: "Consumo Básico" },
  { ticker: "K",     name: "Kellanova",              sector: "Consumo Básico" },
  { ticker: "CPB",   name: "Campbell's",             sector: "Consumo Básico" },
  { ticker: "MKC",   name: "McCormick",              sector: "Consumo Básico" },
  { ticker: "SJM",   name: "J.M. Smucker",           sector: "Consumo Básico" },
  { ticker: "HRL",   name: "Hormel Foods",           sector: "Consumo Básico" },
  { ticker: "TSN",   name: "Tyson Foods",            sector: "Consumo Básico" },
  { ticker: "CAG",   name: "Conagra Brands",         sector: "Consumo Básico" },
  { ticker: "KR",    name: "Kroger",                 sector: "Consumo Básico" },
  { ticker: "SYY",   name: "Sysco",                  sector: "Consumo Básico" },
  { ticker: "WBA",   name: "Walgreens Boots",        sector: "Consumo Básico" },
  { ticker: "KVUE",  name: "Kenvue",                 sector: "Consumo Básico" },
  { ticker: "CHD",   name: "Church & Dwight",        sector: "Consumo Básico" },
  { ticker: "CLX",   name: "Clorox",                 sector: "Consumo Básico" },
  { ticker: "EL",    name: "Estée Lauder",           sector: "Consumo Básico" },
  { ticker: "BG",    name: "Bunge Global",           sector: "Consumo Básico" },
  { ticker: "TAP",   name: "Molson Coors",           sector: "Consumo Básico" },
  { ticker: "KDP",   name: "Keurig Dr Pepper",       sector: "Consumo Básico" },
  // ── Salud ─────────────────────────────────────────────────────────────────────
  { ticker: "LLY",   name: "Eli Lilly",              sector: "Salud" },
  { ticker: "UNH",   name: "UnitedHealth Group",     sector: "Salud" },
  { ticker: "JNJ",   name: "Johnson & Johnson",      sector: "Salud" },
  { ticker: "MRK",   name: "Merck",                  sector: "Salud" },
  { ticker: "ABBV",  name: "AbbVie",                 sector: "Salud" },
  { ticker: "ABT",   name: "Abbott Laboratories",    sector: "Salud" },
  { ticker: "TMO",   name: "Thermo Fisher",          sector: "Salud" },
  { ticker: "MDT",   name: "Medtronic",              sector: "Salud" },
  { ticker: "ISRG",  name: "Intuitive Surgical",     sector: "Salud" },
  { ticker: "ELV",   name: "Elevance Health",        sector: "Salud" },
  { ticker: "CVS",   name: "CVS Health",             sector: "Salud" },
  { ticker: "CI",    name: "Cigna Group",            sector: "Salud" },
  { ticker: "PFE",   name: "Pfizer",                 sector: "Salud" },
  { ticker: "DHR",   name: "Danaher",                sector: "Salud" },
  { ticker: "SYK",   name: "Stryker",                sector: "Salud" },
  { ticker: "BSX",   name: "Boston Scientific",      sector: "Salud" },
  { ticker: "GILD",  name: "Gilead Sciences",        sector: "Salud" },
  { ticker: "ZTS",   name: "Zoetis",                 sector: "Salud" },
  { ticker: "HCA",   name: "HCA Healthcare",         sector: "Salud" },
  { ticker: "REGN",  name: "Regeneron",              sector: "Salud" },
  { ticker: "BDX",   name: "Becton Dickinson",       sector: "Salud" },
  { ticker: "HUM",   name: "Humana",                 sector: "Salud" },
  { ticker: "MCK",   name: "McKesson",               sector: "Salud" },
  { ticker: "DXCM",  name: "Dexcom",                 sector: "Salud" },
  { ticker: "BIIB",  name: "Biogen",                 sector: "Salud" },
  { ticker: "AMGN",  name: "Amgen",                  sector: "Salud" },
  { ticker: "VRTX",  name: "Vertex Pharmaceuticals", sector: "Salud" },
  { ticker: "EW",    name: "Edwards Lifesciences",   sector: "Salud" },
  { ticker: "BAX",   name: "Baxter International",   sector: "Salud" },
  { ticker: "IQV",   name: "IQVIA Holdings",         sector: "Salud" },
  { ticker: "IDXX",  name: "IDEXX Laboratories",     sector: "Salud" },
  { ticker: "MTD",   name: "Mettler-Toledo",         sector: "Salud" },
  { ticker: "A",     name: "Agilent Technologies",   sector: "Salud" },
  { ticker: "HOLX",  name: "Hologic",                sector: "Salud" },
  { ticker: "RMD",   name: "ResMed",                 sector: "Salud" },
  { ticker: "CRL",   name: "Charles River Labs",     sector: "Salud" },
  { ticker: "PODD",  name: "Insulet Corp",           sector: "Salud" },
  { ticker: "HSIC",  name: "Henry Schein",           sector: "Salud" },
  { ticker: "INCY",  name: "Incyte",                 sector: "Salud" },
  { ticker: "MOH",   name: "Molina Healthcare",      sector: "Salud" },
  { ticker: "CNC",   name: "Centene Corp",           sector: "Salud" },
  { ticker: "MRNA",  name: "Moderna",                sector: "Salud" },
  { ticker: "CTLT",  name: "Catalent",               sector: "Salud" },
  { ticker: "RVTY",  name: "Revvity",                sector: "Salud" },
  { ticker: "SOLV",  name: "Solventum",              sector: "Salud" },
  // ── Finanzas ─────────────────────────────────────────────────────────────────
  { ticker: "BRK-B", name: "Berkshire Hathaway B",  sector: "Finanzas" },
  { ticker: "JPM",   name: "JPMorgan Chase",         sector: "Finanzas" },
  { ticker: "BAC",   name: "Bank of America",        sector: "Finanzas" },
  { ticker: "WFC",   name: "Wells Fargo",            sector: "Finanzas" },
  { ticker: "GS",    name: "Goldman Sachs",          sector: "Finanzas" },
  { ticker: "MS",    name: "Morgan Stanley",         sector: "Finanzas" },
  { ticker: "C",     name: "Citigroup",              sector: "Finanzas" },
  { ticker: "BLK",   name: "BlackRock",              sector: "Finanzas" },
  { ticker: "SCHW",  name: "Charles Schwab",         sector: "Finanzas" },
  { ticker: "AXP",   name: "American Express",       sector: "Finanzas" },
  { ticker: "CB",    name: "Chubb",                  sector: "Finanzas" },
  { ticker: "MMC",   name: "Marsh McLennan",         sector: "Finanzas" },
  { ticker: "PGR",   name: "Progressive Corp",       sector: "Finanzas" },
  { ticker: "AIG",   name: "American Intl Group",    sector: "Finanzas" },
  { ticker: "AFL",   name: "Aflac",                  sector: "Finanzas" },
  { ticker: "ALL",   name: "Allstate",               sector: "Finanzas" },
  { ticker: "MET",   name: "MetLife",                sector: "Finanzas" },
  { ticker: "PRU",   name: "Prudential Financial",   sector: "Finanzas" },
  { ticker: "HIG",   name: "Hartford Financial",     sector: "Finanzas" },
  { ticker: "TFC",   name: "Truist Financial",       sector: "Finanzas" },
  { ticker: "USB",   name: "U.S. Bancorp",           sector: "Finanzas" },
  { ticker: "PNC",   name: "PNC Financial",          sector: "Finanzas" },
  { ticker: "MTB",   name: "M&T Bank",               sector: "Finanzas" },
  { ticker: "FITB",  name: "Fifth Third Bancorp",    sector: "Finanzas" },
  { ticker: "RF",    name: "Regions Financial",      sector: "Finanzas" },
  { ticker: "HBAN",  name: "Huntington Bancshares",  sector: "Finanzas" },
  { ticker: "KEY",   name: "KeyCorp",                sector: "Finanzas" },
  { ticker: "STT",   name: "State Street",           sector: "Finanzas" },
  { ticker: "BX",    name: "Blackstone",             sector: "Finanzas" },
  { ticker: "MCO",   name: "Moody's Corp",           sector: "Finanzas" },
  { ticker: "SPGI",  name: "S&P Global",             sector: "Finanzas" },
  { ticker: "MSCI",  name: "MSCI Inc",               sector: "Finanzas" },
  { ticker: "ICE",   name: "Intercontinental Exchange", sector: "Finanzas" },
  { ticker: "NDAQ",  name: "Nasdaq Inc",             sector: "Finanzas" },
  { ticker: "CME",   name: "CME Group",              sector: "Finanzas" },
  { ticker: "CBOE",  name: "Cboe Global Markets",    sector: "Finanzas" },
  { ticker: "FIS",   name: "Fidelity National Info", sector: "Finanzas" },
  { ticker: "FI",    name: "Fiserv",                 sector: "Finanzas" },
  { ticker: "PYPL",  name: "PayPal",                 sector: "Finanzas" },
  { ticker: "V",     name: "Visa",                   sector: "Finanzas" },
  { ticker: "MA",    name: "Mastercard",             sector: "Finanzas" },
  { ticker: "COF",   name: "Capital One",            sector: "Finanzas" },
  { ticker: "SYF",   name: "Synchrony Financial",    sector: "Finanzas" },
  { ticker: "DFS",   name: "Discover Financial",     sector: "Finanzas" },
  { ticker: "AMP",   name: "Ameriprise Financial",   sector: "Finanzas" },
  { ticker: "IVZ",   name: "Invesco",                sector: "Finanzas" },
  { ticker: "BEN",   name: "Franklin Resources",     sector: "Finanzas" },
  { ticker: "TROW",  name: "T. Rowe Price",          sector: "Finanzas" },
  { ticker: "RJF",   name: "Raymond James",          sector: "Finanzas" },
  { ticker: "PFG",   name: "Principal Financial",    sector: "Finanzas" },
  { ticker: "CFG",   name: "Citizens Financial",     sector: "Finanzas" },
  { ticker: "AIZ",   name: "Assurant",               sector: "Finanzas" },
  { ticker: "ACGL",  name: "Arch Capital",           sector: "Finanzas" },
  // ── Industrial ───────────────────────────────────────────────────────────────
  { ticker: "RTX",   name: "RTX Corp",               sector: "Industrial" },
  { ticker: "GE",    name: "GE Aerospace",           sector: "Industrial" },
  { ticker: "HON",   name: "Honeywell",              sector: "Industrial" },
  { ticker: "UNP",   name: "Union Pacific",          sector: "Industrial" },
  { ticker: "CAT",   name: "Caterpillar",            sector: "Industrial" },
  { ticker: "DE",    name: "John Deere",             sector: "Industrial" },
  { ticker: "LMT",   name: "Lockheed Martin",        sector: "Industrial" },
  { ticker: "ETN",   name: "Eaton Corp",             sector: "Industrial" },
  { ticker: "EMR",   name: "Emerson Electric",       sector: "Industrial" },
  { ticker: "CARR",  name: "Carrier Global",         sector: "Industrial" },
  { ticker: "OTIS",  name: "Otis Worldwide",         sector: "Industrial" },
  { ticker: "GD",    name: "General Dynamics",       sector: "Industrial" },
  { ticker: "HII",   name: "Huntington Ingalls",     sector: "Industrial" },
  { ticker: "NOC",   name: "Northrop Grumman",       sector: "Industrial" },
  { ticker: "LHX",   name: "L3Harris Technologies",  sector: "Industrial" },
  { ticker: "TDG",   name: "TransDigm Group",        sector: "Industrial" },
  { ticker: "TXT",   name: "Textron",                sector: "Industrial" },
  { ticker: "TT",    name: "Trane Technologies",     sector: "Industrial" },
  { ticker: "PCAR",  name: "PACCAR",                 sector: "Industrial" },
  { ticker: "CMI",   name: "Cummins",                sector: "Industrial" },
  { ticker: "CTAS",  name: "Cintas",                 sector: "Industrial" },
  { ticker: "ROL",   name: "Rollins",                sector: "Industrial" },
  { ticker: "FAST",  name: "Fastenal",               sector: "Industrial" },
  { ticker: "CPRT",  name: "Copart",                 sector: "Industrial" },
  { ticker: "EXPD",  name: "Expeditors Intl",        sector: "Industrial" },
  { ticker: "NSC",   name: "Norfolk Southern",       sector: "Industrial" },
  { ticker: "CSX",   name: "CSX Corp",               sector: "Industrial" },
  { ticker: "UPS",   name: "United Parcel Service",  sector: "Industrial" },
  { ticker: "FDX",   name: "FedEx",                  sector: "Industrial" },
  { ticker: "WAB",   name: "Wabtec Corp",            sector: "Industrial" },
  { ticker: "GWW",   name: "W.W. Grainger",          sector: "Industrial" },
  { ticker: "SNA",   name: "Snap-on",                sector: "Industrial" },
  { ticker: "ITW",   name: "Illinois Tool Works",    sector: "Industrial" },
  { ticker: "ROK",   name: "Rockwell Automation",    sector: "Industrial" },
  { ticker: "AME",   name: "AMETEK",                 sector: "Industrial" },
  { ticker: "PH",    name: "Parker-Hannifin",        sector: "Industrial" },
  { ticker: "DOV",   name: "Dover Corp",             sector: "Industrial" },
  { ticker: "XYL",   name: "Xylem",                  sector: "Industrial" },
  { ticker: "HUBB",  name: "Hubbell",                sector: "Industrial" },
  { ticker: "IR",    name: "Ingersoll Rand",         sector: "Industrial" },
  { ticker: "VRSK",  name: "Verisk Analytics",       sector: "Industrial" },
  { ticker: "ODFL",  name: "Old Dominion Freight",   sector: "Industrial" },
  { ticker: "NDSN",  name: "Nordson Corp",           sector: "Industrial" },
  { ticker: "LDOS",  name: "Leidos Holdings",        sector: "Industrial" },
  { ticker: "J",     name: "Jacobs Solutions",       sector: "Industrial" },
  { ticker: "DRS",   name: "Leonardo DRS",           sector: "Industrial" },
  { ticker: "HWM",   name: "Howmet Aerospace",       sector: "Industrial" },
  { ticker: "PWR",   name: "Quanta Services",        sector: "Industrial" },
  { ticker: "URI",   name: "United Rentals",         sector: "Industrial" },
  { ticker: "WM",    name: "Waste Management",       sector: "Industrial" },
  { ticker: "RSG",   name: "Republic Services",      sector: "Industrial" },
  { ticker: "TRMB",  name: "Trimble",                sector: "Industrial" },
  { ticker: "GNRC",  name: "Generac Holdings",       sector: "Industrial" },
  { ticker: "TFX",   name: "Teleflex",               sector: "Industrial" },
  { ticker: "SWK",   name: "Stanley Black & Decker", sector: "Industrial" },
  { ticker: "DAL",   name: "Delta Air Lines",        sector: "Industrial" },
  { ticker: "UAL",   name: "United Airlines",        sector: "Industrial" },
  { ticker: "LUV",   name: "Southwest Airlines",     sector: "Industrial" },
  { ticker: "WRK",   name: "WestRock",               sector: "Industrial" },
  { ticker: "DAY",   name: "Dayforce",               sector: "Industrial" },
  // ── Energía ──────────────────────────────────────────────────────────────────
  { ticker: "XOM",   name: "ExxonMobil",             sector: "Energía" },
  { ticker: "CVX",   name: "Chevron",                sector: "Energía" },
  { ticker: "COP",   name: "ConocoPhillips",         sector: "Energía" },
  { ticker: "EOG",   name: "EOG Resources",          sector: "Energía" },
  { ticker: "SLB",   name: "SLB",                    sector: "Energía" },
  { ticker: "MPC",   name: "Marathon Petroleum",     sector: "Energía" },
  { ticker: "VLO",   name: "Valero Energy",          sector: "Energía" },
  { ticker: "PSX",   name: "Phillips 66",            sector: "Energía" },
  { ticker: "DVN",   name: "Devon Energy",           sector: "Energía" },
  { ticker: "HAL",   name: "Halliburton",            sector: "Energía" },
  { ticker: "OXY",   name: "Occidental Petroleum",  sector: "Energía" },
  { ticker: "APA",   name: "APA Corp",               sector: "Energía" },
  { ticker: "HES",   name: "Hess Corp",              sector: "Energía" },
  { ticker: "FANG",  name: "Diamondback Energy",     sector: "Energía" },
  { ticker: "TRGP",  name: "Targa Resources",        sector: "Energía" },
  { ticker: "WMB",   name: "Williams Companies",     sector: "Energía" },
  { ticker: "OKE",   name: "ONEOK",                  sector: "Energía" },
  { ticker: "KMI",   name: "Kinder Morgan",          sector: "Energía" },
  { ticker: "BKR",   name: "Baker Hughes",           sector: "Energía" },
  { ticker: "MRO",   name: "Marathon Oil",           sector: "Energía" },
  { ticker: "NRG",   name: "NRG Energy",             sector: "Energía" },
  { ticker: "AES",   name: "AES Corp",               sector: "Energía" },
  { ticker: "FSLR",  name: "First Solar",            sector: "Energía" },
  { ticker: "ENPH",  name: "Enphase Energy",         sector: "Energía" },
  // ── Materiales ───────────────────────────────────────────────────────────────
  { ticker: "LIN",   name: "Linde",                  sector: "Materiales" },
  { ticker: "SHW",   name: "Sherwin-Williams",       sector: "Materiales" },
  { ticker: "ECL",   name: "Ecolab",                 sector: "Materiales" },
  { ticker: "APD",   name: "Air Products",           sector: "Materiales" },
  { ticker: "PPG",   name: "PPG Industries",         sector: "Materiales" },
  { ticker: "DD",    name: "DuPont",                 sector: "Materiales" },
  { ticker: "CTVA",  name: "Corteva",                sector: "Materiales" },
  { ticker: "ALB",   name: "Albemarle",              sector: "Materiales" },
  { ticker: "NEM",   name: "Newmont",                sector: "Materiales" },
  { ticker: "FCX",   name: "Freeport-McMoRan",       sector: "Materiales" },
  { ticker: "CF",    name: "CF Industries",          sector: "Materiales" },
  { ticker: "MOS",   name: "Mosaic",                 sector: "Materiales" },
  { ticker: "NUE",   name: "Nucor",                  sector: "Materiales" },
  { ticker: "STLD",  name: "Steel Dynamics",         sector: "Materiales" },
  { ticker: "BALL",  name: "Ball Corp",              sector: "Materiales" },
  { ticker: "SEE",   name: "Sealed Air",             sector: "Materiales" },
  { ticker: "AVY",   name: "Avery Dennison",         sector: "Materiales" },
  { ticker: "IFF",   name: "International Flavors",  sector: "Materiales" },
  { ticker: "EMN",   name: "Eastman Chemical",       sector: "Materiales" },
  { ticker: "FMC",   name: "FMC Corp",               sector: "Materiales" },
  { ticker: "CE",    name: "Celanese",               sector: "Materiales" },
  { ticker: "LYB",   name: "LyondellBasell",         sector: "Materiales" },
  { ticker: "IP",    name: "International Paper",    sector: "Materiales" },
  { ticker: "PKG",   name: "Packaging Corp",         sector: "Materiales" },
  { ticker: "MLM",   name: "Martin Marietta",        sector: "Materiales" },
  { ticker: "VMC",   name: "Vulcan Materials",       sector: "Materiales" },
  // ── Servicios Públicos ────────────────────────────────────────────────────────
  { ticker: "NEE",   name: "NextEra Energy",         sector: "Servicios Púb." },
  { ticker: "SO",    name: "Southern Company",       sector: "Servicios Púb." },
  { ticker: "DUK",   name: "Duke Energy",            sector: "Servicios Púb." },
  { ticker: "AEP",   name: "American Electric Power",sector: "Servicios Púb." },
  { ticker: "EXC",   name: "Exelon",                 sector: "Servicios Púb." },
  { ticker: "XEL",   name: "Xcel Energy",            sector: "Servicios Púb." },
  { ticker: "WEC",   name: "WEC Energy",             sector: "Servicios Púb." },
  { ticker: "ES",    name: "Eversource Energy",      sector: "Servicios Púb." },
  { ticker: "AEE",   name: "Ameren",                 sector: "Servicios Púb." },
  { ticker: "ETR",   name: "Entergy",                sector: "Servicios Púb." },
  { ticker: "EIX",   name: "Edison International",   sector: "Servicios Púb." },
  { ticker: "PCG",   name: "PG&E Corp",              sector: "Servicios Púb." },
  { ticker: "DTE",   name: "DTE Energy",             sector: "Servicios Púb." },
  { ticker: "ED",    name: "Consolidated Edison",    sector: "Servicios Púb." },
  { ticker: "LNT",   name: "Alliant Energy",         sector: "Servicios Púb." },
  { ticker: "NI",    name: "NiSource",               sector: "Servicios Púb." },
  { ticker: "PEG",   name: "PSEG",                   sector: "Servicios Púb." },
  { ticker: "FE",    name: "FirstEnergy",            sector: "Servicios Púb." },
  { ticker: "SRE",   name: "Sempra",                 sector: "Servicios Púb." },
  { ticker: "AWK",   name: "American Water Works",   sector: "Servicios Púb." },
  { ticker: "CMS",   name: "CMS Energy",             sector: "Servicios Púb." },
  { ticker: "PPL",   name: "PPL Corp",               sector: "Servicios Púb." },
  { ticker: "PNW",   name: "Pinnacle West Capital",  sector: "Servicios Púb." },
  { ticker: "D",     name: "Dominion Energy",        sector: "Servicios Púb." },
  { ticker: "ATO",   name: "Atmos Energy",           sector: "Servicios Púb." },
  { ticker: "CEG",   name: "Constellation Energy",   sector: "Servicios Púb." },
  // ── Real Estate ──────────────────────────────────────────────────────────────
  { ticker: "AMT",   name: "American Tower",         sector: "Real Estate" },
  { ticker: "PLD",   name: "Prologis",               sector: "Real Estate" },
  { ticker: "CCI",   name: "Crown Castle",           sector: "Real Estate" },
  { ticker: "EQIX",  name: "Equinix",                sector: "Real Estate" },
  { ticker: "PSA",   name: "Public Storage",         sector: "Real Estate" },
  { ticker: "DLR",   name: "Digital Realty",         sector: "Real Estate" },
  { ticker: "O",     name: "Realty Income",          sector: "Real Estate" },
  { ticker: "WELL",  name: "Welltower",              sector: "Real Estate" },
  { ticker: "SPG",   name: "Simon Property Group",   sector: "Real Estate" },
  { ticker: "EQR",   name: "Equity Residential",     sector: "Real Estate" },
  { ticker: "ESS",   name: "Essex Property Trust",   sector: "Real Estate" },
  { ticker: "MAA",   name: "Mid-America Apartment",  sector: "Real Estate" },
  { ticker: "VTR",   name: "Ventas",                 sector: "Real Estate" },
  { ticker: "WY",    name: "Weyerhaeuser",           sector: "Real Estate" },
  { ticker: "AVB",   name: "AvalonBay Communities",  sector: "Real Estate" },
  { ticker: "ARE",   name: "Alexandria Real Estate", sector: "Real Estate" },
  { ticker: "CSGP",  name: "CoStar Group",           sector: "Real Estate" },
  { ticker: "SBAC",  name: "SBA Communications",     sector: "Real Estate" },
  { ticker: "INVH",  name: "Invitation Homes",       sector: "Real Estate" },
  { ticker: "EXR",   name: "Extra Space Storage",    sector: "Real Estate" },
  { ticker: "UDR",   name: "UDR Inc",                sector: "Real Estate" },
  { ticker: "HST",   name: "Host Hotels",            sector: "Real Estate" },
  { ticker: "KIM",   name: "Kimco Realty",           sector: "Real Estate" },
  { ticker: "REG",   name: "Regency Centers",        sector: "Real Estate" },
  { ticker: "IRM",   name: "Iron Mountain",          sector: "Real Estate" },
  { ticker: "VICI",  name: "VICI Properties",        sector: "Real Estate" },
]

// v7/quote requiere auth desde 2025; usamos v8/chart por ticker (sin auth)
async function fetchYFChart(ticker: string): Promise<{ lastPrice: number | null; change1DPct: number | null } | null> {
  for (const host of ["query1.finance.yahoo.com", "query2.finance.yahoo.com"]) {
    try {
      const res = await fetch(
        `https://${host}/v8/finance/chart/${encodeURIComponent(ticker)}?interval=1d&range=5d`,
        { headers: YF_HEADERS, signal: AbortSignal.timeout(8_000) },
      )
      if (!res.ok) continue
      const json = await res.json() as { chart?: { result?: unknown[] } }
      const result = json?.chart?.result?.[0] as {
        indicators?: { quote?: Array<{ close?: (number | null)[] }> }
      } | undefined
      if (!result) continue
      const closes = result.indicators?.quote?.[0]?.close ?? []
      const valid: number[] = closes.filter((c): c is number => c != null)
      if (!valid.length) continue
      const last = valid[valid.length - 1]
      const prev = valid.length > 1 ? valid[valid.length - 2] : null
      const change1DPct = prev && prev > 0 ? ((last - prev) / prev) * 100 : 0
      return { lastPrice: last, change1DPct }
    } catch { /* next host */ }
  }
  return null
}

const _cache: Record<string, { data: unknown; expiry: number }> = {}
function getCached<T>(k: string): T | null {
  const e = _cache[k]
  return e && e.expiry > Date.now() ? (e.data as T) : null
}
function setCached(k: string, d: unknown, ttlSec: number) {
  _cache[k] = { data: d, expiry: Date.now() + ttlSec * 1000 }
}

export async function GET() {
  const cached = getCached<unknown[]>("usa_stocks")
  if (cached) return NextResponse.json({ data: cached, cached: true })

  // v8/chart en chunks de 50 tickers: evita saturar YF con 400+ conexiones simultáneas
  const allTickers = SP500.map((s) => s.ticker)
  const CHUNK = 50
  const quoteMap = new Map<string, { lastPrice: number | null; change1DPct: number | null } | null>()

  for (let i = 0; i < allTickers.length; i += CHUNK) {
    const batch = allTickers.slice(i, i + CHUNK)
    const entries = await Promise.all(batch.map(async (t) => [t, await fetchYFChart(t)] as const))
    for (const [t, d] of entries) quoteMap.set(t, d)
  }

  const results = SP500.map((stock) => {
    const q = quoteMap.get(stock.ticker)
    return {
      ticker:      stock.ticker,
      name:        stock.name,
      sector:      stock.sector,
      market:      "S&P 500",
      currency:    "USD",
      lastPrice:   q?.lastPrice ?? null,
      change1DPct: q?.change1DPct ?? null,
    }
  })

  setCached("usa_stocks", results, 900) // 15 min
  return NextResponse.json({ data: results, updated_at: new Date().toISOString() })
}
